### ISSUE TITLE
Associate View - New Interview on Firefox

### ISSUE THREAD

**Issue by MTichael** [revaturelabs/trackforce#1064]
Creating a new Interview relies on Chrome or Opera for the Date field format. 
On any other browser (I used Firefox) the field has placeholder "Date" and no format information. 
This should be changed by updating the placeholder and implementing one of the following:

**1.** using the FormBuilder **Validators** in Angular to check the input value and deny incorrect date-time    formats. The validators use regex and can be bound to the input field in the HTML. 
**2.**  adding a check for browser version in the Angular project to use different field settings for each browser. This will likely result in using one of the other options for specific browsers. 
**3.** Separate the datetime-local input field into two fields for date and time inputs. These input fields are widely supported by the majority of browsers, including all the most common browsers. 

Issue Created Batch 1811

**Comment by ryan-schlientz** [comment]
This is now resolved.

**Comment by Michael-Salato-DU** [comment]
Implemented option #3. We made two separate fields. One for date and one for time. This was done for creating a new interview and updating an interview.
