### ISSUE TITLE
Produce a database model diagram for us.

### ISSUE THREAD

**Issue by Kieldro** [revaturelabs/trackforce#285]
@Ed-Mar

**Comment by Kieldro** [comment]
Here is ERD Entity Relationship Diagram for our DB
https://drive.google.com/open?id=1qpmJYSAsTlONoZ-21FQQllzEdBavCRGZvuKEHVhZMLY
@hpark12  Thanks Rich

**Comment by YoshiKirishima** [comment]
Nice, I love SC2
