### ISSUE TITLE
Database Button Responses

### ISSUE THREAD

**Issue by Dackleyjr1** [revaturelabs/trackforce#30]
Situation: IN SPRING TOOL SUITE ONLY
Delete and Populate button will successfully execute the first time they are clicked, With proper message in response being displayed.
Continual clicks however, will display response text indicating success,without performing the respective action.
This exists through STS browser refresh and server restart. Only closing and reopening STS seems to fix.

This issue does not arise on an actual chrome browser.

**Comment by VaethMMR** [comment]
The buttons work. However, each press is a new request to the DB. This can cause an issue for the connection pool as it may exhaust all available connections. 

A future approach can be to restrict the executions to one at a time using synchronize and make the operations atomic. Then have some checksum for pool exhaustion before making the request to the db.

**Comment by StrollingFellow** [comment]
The buttons have been removed.
