### ISSUE TITLE
Create a working Restrict Access using JWT

### ISSUE THREAD

**Issue by Ed-Mar** [revaturelabs/trackforce#333]
Have it so that user groups actually change views, access, and available functions

**Comment by Kieldro** [comment]
@mitch-harrison @CuongDNguyen and I have the code working for JWT authentication for InterviewResource.createInterview(). Just needs to be added to every single URI in the resource package.

**Comment by Kieldro** [comment]
Authentication is done on jersey side. Angular controls the view
