### ISSUE TITLE
Data on home page graphs not properly recieved

### ISSUE THREAD

**Issue by skaggs1995** [revaturelabs/trackforce#422]
"The bottom two graphs don't properly pull up the more detailed data when the pie chart in the graph is clicked"

"login as admin, Go to home page, click the pie chart elements in bottom two graphs, click any of the graph options that show up"

**Comment by AmeliaDunn** [comment]
being worked on in branch salesHomeCharts

**Comment by AmeliaDunn** [comment]
closed by merge #498
