### ISSUE TITLE
Limit creation of users in some way

### ISSUE THREAD

**Issue by skaggs1995** [revaturelabs/trackforce#423]
Can flood the database with associates and trainers, which will never get approved, but simply sit there unused.

Possibly remove associates that are not approved after 30 days or so.

**Comment by dvosecky** [comment]
A stored procedure has been added to the database that removes users that have not been approved within 30 days of registering. This involved adding a new column to tf_user, tf_user_register_date. The stored procedure is executed daily from SchedulePendingUserCleanup.java.

**Comment by erikmoore001** [comment]
Stored procedure added, and created a thread that is on a timer. Thread runs every 24 hours and calls the stored procedure.
