### ISSUE TITLE
500 Error for getAllInterviews

### ISSUE THREAD

**Issue by jesseskipper14** [revaturelabs/trackforce#444]
In package com.revature.resources.InterviewResource

The method is getAllInterviews(). I am unable to get a valid response from either within the test code or from Postman. Making a get request for http://52.87.205.55:8086/TrackForce/ or http://52.87.205.55:8086/TrackForce/{id} will always return a 500 NullPointerException

com.revature.resources.InterviewResource.getAllInterviews(InterviewResource.java:99)

**Comment by aaalfaro** [comment]
This method has since been reworked
