### ISSUE TITLE
500 error for getTrainer

### ISSUE THREAD

**Issue by jesseskipper14** [revaturelabs/trackforce#463]
HTTP Status 500 - java.lang.IllegalArgumentException: org.hibernate.QueryException: could not resolve property: tf_trainer_id of: com.revature.entity.TfTrainer [from com.revature.entity.TfTrainer t where t.tf_trainer_id like :trainerId

This seems to be a problem with the hibernate logic. I am unable to access any trainer with the resource as it currently is written.

**Comment by StrollingFellow** [comment]
It was getting trainer by trainer id, instead of getting trainer by userid
