### ISSUE TITLE
CRITICAL: createTrainer in TrainerResource does not seem to be working

### ISSUE THREAD

**Issue by jesseskipper14** [revaturelabs/trackforce#474]
I can call the resource which will return a 201 (content created) but there is no new trainer in the database after the call to reflect the change. It also does not appear that the trainer is going into the user table either. I am unsure where the trainer is going.

**Comment by jesseskipper14** [comment]
Update: Got an error code

org.hibernate.MappingException: Unknown entity: org.hibernate.engine.transaction.internal.TransactionImpl

**Comment by StrollingFellow** [comment]
Was accidentally trying to persist a Transaction in createHibernateTransaction, it's been resolved.
