### ISSUE TITLE
Bar/Pie/Polar Charts not loading for Unmapped chart

### ISSUE THREAD

**Issue by thebrewer7** [revaturelabs/trackforce#578]
Reproduce:
1. Login as an admin
2. Click the "training" slice of the "Unmapped" pie chart, which should be the bottom right pie chart.
3. Expect to see: the bar/pie/polar chart above the pie chart that loads on the bottom. For reference click any other slice of any other pie chart from the "home" page for the admin.
4. Actually see: nothing loads on the top section where the chart should be.
This bug only happens when you click on that specific slice of that specific pie chart. All the rest appear to work.

**Comment by auhwang** [comment]
fixed in 4fd30cc048703e863a167562cc195278a32fc78e
