### ISSUE TITLE
Client List doesn't populate before search is available

### ISSUE THREAD

**Issue by jckuhl** [revaturelabs/trackforce#636]
# Front end bug:

The client list on the client list page populates slowly, therefore the search feature is faulty.  It will fail to find a client who is on the list if the user searches the moment he enters the screen.  Search box should be disabled until the whole list is loaded, or the database should be pulled after (or during) the user enters his search

# Steps to reproduce:

* Go to Client List.
* Enter "infosys" as soon as it loads.  

Frequently, it will return an empty list as if "infosys" is not in the client list.

**Comment by Quinn-Donnelly** [comment]
#717 has been confirmed to fix this issue.
