### ISSUE TITLE
Trainer Batch List Isn't Fetching

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/trackforce#638]
## Description
On the batch page for the trainer account the batch list is only being fetched when the page loads. There is a submit button on the page to set the date range and then submit to receive the list of batches for that range. This submit and reset button are not implemented.

### Steps to Reproduce
1. Login as trainer
2. Open Network Monitor (F12) -> click network
3. Click on Batch List
4. You will see a request go out to get the preset range
5. Change the date range using datepicker
6. Click Submit

*At this point no request is dispatched, the same is true for reset.*

**Comment by apeterson7** [comment]
Fixed the issue by setting filteredBatches to batches and dataReady to true within the subscribe function when userRole === 2.   Changed the field being used to check if a batches trainer matches the logged in trainer (using the trainer's associated user's id).  Added default start and end dates (the same ones that an Administrator see's by default)
