### ISSUE TITLE
Columns under the Associate List Tab can't be sorted

### ISSUE THREAD

**Issue by huangl6** [revaturelabs/trackforce#639]
### **Description**
The columns under the Associate don't have an option to be sorted.

### **Steps to Reproduce**
1. Login to TestAdmin
2. Click the Associate List Tab
3. Try clicking on any of the column names.

**Comment by jckuhl** [comment]
I'm handling this one.

**Comment by Quinn-Donnelly** [comment]
911bc49 resolved this which was merged in PR #701
