### ISSUE TITLE
Cannot see mapped associates in predictions tab 

### ISSUE THREAD

**Issue by steveLoayza** [revaturelabs/trackforce#641]
As a staging manger, you should be able to view all associates who are mapped to a client in the predictions tab

**Steps to reproduce**
	1. Login as staging manager
	2. Navigate to predictions tab
	3. No info is available regarding mapped associates

**Comment by steveLoayza** [comment]
I'll look into this

**Comment by Quinn-Donnelly** [comment]
#728 Resolves this
