### ISSUE TITLE
Screen shakes when moving mouse on individual Associates page

### ISSUE THREAD

**Issue by huangl6** [revaturelabs/trackforce#643]
### **Description**
When moving mouse around the screen on an individual associate's page (i.e. http://34.227.178.103:8090/NGTrackForce/#/form-comp/5238), the screen "shakes" because a scroll bar is loaded and then unloaded.

### **Steps to Reproduce**
1. Login to TestAdmin
2. Click the Associates List
3. Click on any Associate's ID. 
4. Move mouse around on the screen

It should just be a CSS margin fix. Low priority.

**Comment by Quinn-Donnelly** [comment]
This bug was resolved in a previous PR.
