### ISSUE TITLE
Can't add information to interview page

### ISSUE THREAD

**Issue by steveLoayza** [revaturelabs/trackforce#645]
### Description
As a staging manager, you should be able to add info to an associate's interview page. Should be able to add Client feedback to the interview page and optionally display feedback

### Steps to reproduce
	1. Login as staging manger
	2. Navigate to associate list
	3. Click on any associate by id
	4. Cannot update status or edit interview information or add feedback

**Comment by huangl6** [comment]
me

**Comment by huangl6** [comment]
Partially fixed, the front end functionality is there, however there is some permission error on the backend that prevents the Staging Manager and/or Sales to view/edit the Interview information. 

TestAdmin (administrator account) has full functionality.

**Comment by dvosecky** [comment]
For some reason, calling AuthenticationService.getUserRole() from within InterviewDetailsComponent always returns undefined. We were unable to determine why, and fixed this issue by making an asynchronous call to getUserRoleFirst() instead.
