### ISSUE TITLE
Update buttons on individual associate page does nothing

### ISSUE THREAD

**Issue by huangl6** [revaturelabs/trackforce#646]
### **Description**
The "Update Status" and "Update Associate" buttons have no functionality at the moment.

### **Steps to reproduce**
1. Login to TestAdmin
2. Click the Associates List tab
3. Click on any associate. 
4. Click either of the update buttons. Nothing happens.
5. Populate fields
6. Try clicking update buttons again. Still, nothing happens

**Comment by Quinn-Donnelly** [comment]
Fixed UI didn't inform user #716 resolves this.
