### ISSUE TITLE
Registering a user gives no confirmation

### ISSUE THREAD

**Issue by jckuhl** [revaturelabs/trackforce#647]
# Bug, front end, register screen
Registering a user gives no confirmation that a user has been registered, until the user has been added.  This takes several seconds, in the meanwhile, the user doesn't have any impression that anything is happening.  This could lead to the user being confused and trying to register again.

# Steps to Reproduce
* Log out (if logged in)
* Click on register and fill out the information
* Nothing happens for several seconds until a confirmation message appears

**Comment by Quinn-Donnelly** [comment]
Partial solution needs to inform using Pending then on complete show the message it currently shows.

**Comment by ravneetb** [comment]
Included a loading circle after user clicks 'Register'.
