### ISSUE TITLE
Bug: Batch List Submit/Reset Buttons Non-Functional

### ISSUE THREAD

**Issue by Wu-Kevin** [revaturelabs/trackforce#648]
Potentially inconsequential due to lack of data to display.

### Steps to Reproduce Bug:
1. Log in as Trainer
2. Navigate to "Batch List"
3. Submit any "Start Date" and "End Date"
4. Click "Submit" or "Reset" - no data will be shown, dates will not be reset, etc.

**Comment by Quinn-Donnelly** [comment]
Duplicate of #638
