### ISSUE TITLE
get all clients method not returning all clients

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#654]
In client.service.ts (frontend) it is noted:
"This method was meant to return all clients with mapped associates."
"But is currently not used due to incorrect query in the back-end."

This is referring to the "getAllClientsWithMappedAssociates" method.
The querry should be reviewed, corrected and tested.

located in com.revature.daoimpl.ClientDaoImpl.java

**Comment by jdpressley5** [comment]
On Hold until Full DB available.

**Comment by TaylorBrodowsky** [comment]
now returns all clients and quickly
