### ISSUE TITLE
Prediction Tab form constraints inconsistent with error message

### ISSUE THREAD

**Issue by huangl6** [revaturelabs/trackforce#658]
### **Description**
The error message says "Please enter a number between 1 and 1000". It allows the user to enter 1 (as it should), however, it does not allow the user to enter 1000.

### **Steps to reproduce**
1. Login to TestAdmin
2. Click the Predictions Tab
3. Click on any of the Associates Needed tabs and attempt to add 1000.

**Comment by huangl6** [comment]
ME FIX

**Comment by Quinn-Donnelly** [comment]
Resolved Via mentioned merge.
