### ISSUE TITLE
Update button is not working

### ISSUE THREAD

**Issue by Vivi-Vo** [revaturelabs/trackforce#662]
**Steps to reproduce**

1. Pull up login home page
2. Login as an Associate
3. Click on Interview tab
4. Scroll down My Interviews table
5. Click on one of the Update button

**Comment by Vivi-Vo** [comment]
Not a bug. Update button updated the interview date in the database, but no confirm message pop up. Working on creating a success alert after data is updated.

**Comment by Quinn-Donnelly** [comment]
#716 Closes this issue.
