### ISSUE TITLE
AssociateResource.java needs security enhancements

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#665]
- [x] @PUT method "approveAssociate" has no token verification; anyone could call this
method and approve an associate.

- [x] @GET method "getNAssociates" appears to be an unfinished attempt to return an
arbitrary number of associates from the database. It is called from the frontend
but provides no value. This is potentially a major performance issue and should
either be fully implemented or disabled/removed. 

Frontend teams should look 
into the reason this method is called. Also,

- [x] there is no token or error checking
for this method.

**Comment by Bioshock667** [comment]
@IMMcC4486 has added token authorization to PUT /associate/{id}/approve

**Comment by IMMcC4486** [comment]
approveAssociate now validates using a token. Without a token, the access and status is Unauthorized. Associates can now be approved by admin and trainer roles (verified by their token). The other roles will have a Forbidden status and be unable to make approvals.

**Comment by mycluster** [comment]
method "getNAssociates" is no longer used because it was replaced with pagenation. The former method was deprecated, and thus removed.
