### ISSUE TITLE
BatchDaoImpl.java not returning proper value

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#666]
"getBatch(String)" method will querry all batches and return the first
result, not the one specified. This should have failed a unit test.

located in com.revature.daoimpl.BatchDaoImpl.java

**Comment by jdpressley5** [comment]
This method is only used in unit testing. It is not used by the angular app in any way. Do we spend the time to fix the query or remove the 3 unit that use it?
