### ISSUE TITLE
ClientDaoImpl.java not following Dao design pattern

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#667]
The "getEndClient" method returns a TfEndClient (not TfClient) deviating from
the DAO design pattern. What is a TfEndClient? It is not clear from the ERD
what this class even represents.

located in com.revature.daoimpl.ClientDaoImpl.java

**Comment by jdpressley5** [comment]
This is due to the way mappings to clients work with revature. Clients are the companies that we send employees to. End client is the employeer the associate ends up at. For example (Hired to Accenture, they send you to work at Fannie May). This does differ in design pattern but is not an issue.
