### ISSUE TITLE
Prediction tab allows start and end date from the year 0001.

### ISSUE THREAD

**Issue by huangl6** [revaturelabs/trackforce#668]
### **Description**
You can set the start and end date to the year 0001. These should be constrained to atleast 2017.

### **Steps to Reproduce**
1. Login to TestAdmin
2. Click the Predictions Tab
3. Set the Start and End Date year to 0001

**Comment by Vivi-Vo** [comment]
me

**Comment by steveLoayza** [comment]
I'll work on this

**Comment by MrDetail56000** [comment]
Fixed

**Comment by TaylorBrodowsky** [comment]
works now
