### ISSUE TITLE
TrainerService.java has several issues with creating new trainers

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#669]
- [x] "createTrainer" method noted to have a broken sequence generator.

- [x] UserService object created and never used. 

I believe these are the reminants of
some bad hacks to get things presentation ready.

located in com.revature.services.TrainerService.java

**Comment by davidcheng1760** [comment]
Created sequence for trainer id. Fixed errors with only allowed to create one user. Creation of trainer is properly created within the database now.
