### ISSUE TITLE
HibernateUtil.java only uses pre-existing threads

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#670]
"multiTransaction" method comments suggest that it needs refactoring. The claim
is that it could create too many threads and harm performance; in reality it
will not "create" any threads only use the ones already waiting in the
ExecutorService.

located in com.revature.utils.HibernateUtil.java

**Comment by MrDetail56000** [comment]
It seems that the comment was in error, the method worked as it was supposed to.
