### ISSUE TITLE
ThreadUtil.java uses a static que and is not effecient

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#672]
This class holds a static queue of Thread executors that are used for each
hibernate operation.
	- [ ] Why? Each call to the servlet has it's own thread, 
	blocking will not be an issue
	-  [ ] This ExecutorService has a limited number of threads (15, hardcoded)
	This creates a potential bottleneck where one did not exist before.
	-  [ ] This design has the potential to throw an unchecked exception
	that was not considered if the queue is empty.
	- [ ] The calling thread immediately waits (blocks) for the Future object to
	finish; no efficiency is gained from any type of concurrency.
	- [ ]  Provided each call to the servlet has its own Session object (and it does)
	there will be no concurrency issues requiring a separate executor thread.

located in com.revature.utils.ThreadUtil.java

**Comment by MrDetail56000** [comment]
After reviewing and working with this code for over a week, I still can not figure out why this design was chosen.  However, it is deeply ingrained in the functionality of every hibernate call.  This could be refactored, but the benefits gained would be marginal.  I am going to close this issue with a "it works well enough" if nobody else opposes.
