### ISSUE TITLE
Update Associate Is Slow

### ISSUE THREAD

**Issue by jckuhl** [revaturelabs/trackforce#673]
Updating an associate is slow enough that it has the potential to break when running down the check boxes.  Specifically, the "Is the associate scheduled for an interview?" checkbox will time out and won't load the next group of check boxes or get marked.  Warnings get thrown in console:

Violation warnings thrown:
[Violations](https://ibb.co/e9oonp)

# Steps to reproduce
* Log in under TestAdmin or Staging Manager
* Go to associate list
* Click an associate
* Run down the check boxes, the "Is the associate scheduled for an interview?" _might_ time out.

**Comment by davidcheng1760** [comment]
Modularizing the Angular Project has fixed this issue.
