### ISSUE TITLE
com.revature.test.admin.cukes.all-files sleep take too long and slow the whole process down

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#675]
Many of the tests wait on page elements to load by invoking Thread.sleep(long)
and hoping that they are visible at the end of the wait. This is certainly not
the way to go about this; look into implicit/explicit WebDriver waits.

I can see why these tests are taking so long.
We must remove EVERY instance of Thread.sleep() and implement proper waits.

located in com.revature.test.admin.cukes.AssociateListCukes.java

**Comment by csiu13** [comment]
Being handled by #695
