### ISSUE TITLE
DbUnit.java unused imports and db connection info hardcoded

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#676]
- [ ] Database connection info, including password are hardcoded into this file.
	Fourtinately, this seems to be a dead connection.
- [ ]  New testing framework used here - org.dbunit - we need to look into this
- [x] Lots of unused imports... "Remove unused imports" it's that easy!

located in com.revature.test.dao.DbUnit.java

**Comment by davidcheng1760** [comment]
We don't have a dbunit anymore.
