### ISSUE TITLE
TrackForce Req 1. The application should be Production ready

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#688]
- [ ]  no bugs (8 bugs)
- [ ] every feature functioning properly (close to yes, confidence low)
- [ ] application should be properly tested. Expect lots of questions on
- [ ] Code Coverage (Percentage of application code that is tested; THANKFULLY SonarQube calculates for us)	
- [ ] Unit	
- [ ] Integration			
- [ ] Regression	
- [ ] Functional (including API)		
- [ ] There are comments made in the code ready for presentation. 	
- [ ] Test coverage should be increased, currently 64% for front end, 40% for back-end. Increase both to 80%x

**Comment by suttergrune** [comment]
This is not an issue. This is the ultimate, primary goal.
