### ISSUE TITLE
TrackForce Req 3. Trainer Role 

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#690]
- [x] As a trainer, the user should only see information pertaining to the trainer's entire batch history
		
- [x] As a trainer, the user should be able to register and edit information 
		
- [x] Associates can register themselves and can get approved by Trainer - this feature is not working
		
- [x] As a trainer, the user should be able to deny approval for an associate who is not in a batch

**Comment by Quinn-Donnelly** [comment]
Steve is working on the final mark on this task.
