### ISSUE TITLE
TrackForce Req 4.Staging Manager Role 

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#691]
- [x] As a staging manager, the user should be able to see data from all batches 	
- [x] As a staging manager, the user should be able to see which Client associates are mapped to in the Predictions tab  - its actually improved
- [x] As a staging manager, the user should be able to add information to a respected associate's Interview page. The user should be able to input the Client's feedback for the Interview and optionally display that Client feedback for the Associate view 	
- [ ] As a staging manager, the user should be able to generate reports about the associates in staging for 		
-  [x] Number of interviews per associate 		
- [ ] Days in staging per associate 	
- [ ] Job Description (provided or not) as well as feedback
- [ ] How they are engaged while in staging (Working on a project, certification preparation, etc)

**Comment by suttergrune** [comment]
Duplicate issue:
The problems outlined in this issue can be viewed on issue #649
