### ISSUE TITLE
TrackForce Req 5. Predictions Tab

### ISSUE THREAD

**Issue by TaylorBrodowsky** [revaturelabs/trackforce#692]
- [x] There currently is functionality for generating predictions for the number of associates available between 2 dates, filtered by technology
- [ ] From the predictions tab, there needs to be functionality to see the breakdown of which Client the associate is mapped to 	
- [ ] Pending item -> we can not see the breakdown of number of associate per client in predictions tab

**Comment by Quinn-Donnelly** [comment]
Vivi is working on this to implement functionality to see how many of the available associates are mapped and unmapped. Once this is complete she will begin work on the ability to show the batch list with those involved in the count. This will enable to staging and delivering to get the information they need.

**Comment by suttergrune** [comment]
Duplicate issue. #640
