### ISSUE TITLE
Fix TestNG tests

### ISSUE THREAD

**Issue by csiu13** [revaturelabs/trackforce#697]
- [ ] make the 16 failing tests pass
- [x] #726 - adds more tests
- [x] #680 
- [x] #681 
- [x] #679
- [x] #678 
- [x] #677 
- [x] #676 
- [ ] #710 
- [x] #942

**Comment by landonRmiller** [comment]
Known issues: hardcoded values on tests that are now wrong.

**Comment by GregoryBriggs** [comment]
- [ ] make the 16 failing tests pass
- [x] #726 - adds more tests
- [x] #680 
- [x] #681 
- [x] #679
- [x] #678 
- [x] #677 
- [x] #676 
- [ ] #710

**Comment by cham207388** [comment]
Fixed all the testNG issues stated on this issues tab.

**Comment by cham207388** [comment]
Test method responsible for adding an interview does not always pass. Check for efficiency.
