### ISSUE TITLE
StatusInfoUtil.getDeepCopyOfStatusInfo refactor

### ISSUE THREAD

**Issue by alif2** [revaturelabs/trackforce#70]
This method is unreadable. Each method call should be assigned to a variable.

**Comment by jacob-hackel** [comment]
???

**Comment by jacob-hackel** [comment]
I don't see why this needs refactoring. It is just a method that returns a new object with a constructor.

**Comment by jacob-hackel** [comment]
I refactored to not use nested method calls.
