### ISSUE TITLE
Implement Global Store

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/trackforce#700]
## Description
There is no store configured in the Angular application therefore all data is refreshed on each page visit slowing down the application heavily.

**Comment by Quinn-Donnelly** [comment]
We will use Observable currently the implementation is clearing out the data this will need investigating. The subscriptions to the observable look to be improperly set.

**Comment by huangl6** [comment]
associate and trainer service

**Comment by jckuhl** [comment]
I also need the trainer service

**Comment by Quinn-Donnelly** [comment]
The PR #746 will implement the fixed associate service. Trainer is up next.

**Comment by Quinn-Donnelly** [comment]
The is only pending on a few services now the others are using Subjects since we were told not to use ngrx.

**Comment by lukasmckela** [comment]
Implemented for some of the primary methods.  Still needs to be added for:

/clients/associates/get/#
/associates/page?startIndex=#&numResults=#
/associates/allAssociates
/skillset
/interviews/associate/#
