### ISSUE TITLE
Cleanup Existing TestNG tests

### ISSUE THREAD

**Issue by csiu13** [revaturelabs/trackforce#710]
all fall under com.revature.test
- [x] cleanup junit.entity
- [x] cleanup junit.util => blocked by #723
- [x] cleanup restAssured
- [ ] cleanup runner
- [ ] cleanup services

**Comment by BSlappey** [comment]
Was not able to integrate the new tests into our final version.  However, the new restassured tests are included in the 1809 google drive folder for the next batch to make use of.
