### ISSUE TITLE
getBatchbyId() in BatchDaoImpl not returning desired value

### ISSUE THREAD

**Issue by ldcapell** [revaturelabs/trackforce#712]
In lines 119 to 124 in BatchDaoImpl under com.revature.daoimpl

getBatchbyId() after being tested returns only the first value of the database and cannot return anything else. Reproducible by running Batch service and replacing the service.getBatchById(1) to service.getBatchById(2) and replacing batch1 to batch 2 in the assert statement. Sysout reveals that it defaults to getting the first field of the database. 

Fix by migrating from native SQL to Criteria for a faster and more reliable query. 

This is definitely a bug.

**Comment by jdpressley5** [comment]
On Hold for testing rewrite

**Comment by jdpressley5** [comment]
Tests appear to have been faked and doesn't actually test the function.
