### ISSUE TITLE
getClient() methods in ClientDaoImpl not working as intended

### ISSUE THREAD

**Issue by ldcapell** [revaturelabs/trackforce#718]
lines 46 to 60 of ClientDaoImpl under com.revature.daoimpl.

getClient() method returns the 1st field of database regardless of what is specified or not. Reproducible in ClientServiceTest by replacing 1's with 2's on methods that call getClient. Both getClient(id) and getClient(name) suffer from this.

Fix by using Criteria for the query instead of Native SQL.

**Comment by jdpressley5** [comment]
Issue in fault testing using mockito. Code works with manual testing as far as determined. Tests will be written for this after new test package is in place.
