### ISSUE TITLE
When an associate creates an interview, they cannot specify a date, nor can they update the date of an existing interview.

### ISSUE THREAD

**Issue by Vivi-Vo** [revaturelabs/trackforce#722]
**Description**
Currently show no message when data is updating.
No failure message when request failed
**Steps to reproduce**
1. Login as associate
2. Click on Interview tab
3. Scroll down to interview board
4. Update the interview date and click the update button

*Update dvosecky 11/6/18*
Currently there is not even an option to enter an interview date, nor update interview dates (no interview dates are displaying at all, even though there is a column for interview dates). This functionality needs to be implemented/fixed before it makes sense to show an "update pending" message.

**Comment by dvosecky** [comment]
Date field input has been added, so the user can enter a date and time for their interview, and they can also update existing interview dates/times. However, the current implementation uses a datetime-local input type, which is not supported by Firefox or Safari, so there are no guidelines to ensure that a user enters a valid datetime format, which is a problem. It works correctly in Chrome.
