### ISSUE TITLE
TrainerServiceTest 3 tests fail because createTrainer() does not work 

### ISSUE THREAD

**Issue by ldcapell** [revaturelabs/trackforce#724]
lines 32 to 35 of TrainerDaoImpl.

Tests from TrainerServiceTest has 3 tests that fail, all of which invoke the createTrainer method. Reproducible from TrainerServiceTest when run with TestNG. 

Might be a bug

**Comment by jdpressley5** [comment]
Faulty tests, Password for TfTrainer is not a field. Testing on this field throws NullPointerException. Create trainer functions the way it should.
