### ISSUE TITLE
Multiple GETs set For Associate Interviews

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/trackforce#731]
## Description
The associate interviews are requested many times before one returns. I have tested and confirmed that this affects the test admin and there are likely more roles that are affected but more investigation would be needed.

### Steps to Reproduce
1. Login as Test Admin
2. Navigate to Batch List
3. Select a Batch (if using the current DB script batch 31 : 1708 Aug14 Java has an associate with interview)
4. Open dev tools and pull up network monitor
5. Select the associate (using the script the associate 717 : WIll Underwood has two interviews)
6. The application will have subbmitted more than a few requests to get the interview information.

 
![image](https://user-images.githubusercontent.com/8989563/44823269-7b4ba300-abcd-11e8-8311-8b9dfae771ee.png)

**Comment by joezay677** [comment]
![image](https://user-images.githubusercontent.com/44207145/48049067-154a4180-e163-11e8-9ee8-feab09bf6b8e.png)

notice that there are two 717's however this is acceptable as they are not both calls to get the interview. One is a call to get the associate and the other is the call for the interview. This call for the interview is only done once now

**Comment by lukasmckela** [comment]
Closing this as appears to be resolved.
