### ISSUE TITLE
Batch List tab in admin user filter doesn't work

### ISSUE THREAD

**Issue by csiu13** [revaturelabs/trackforce#740]
If you use a date that corresponds directly to a batches start and end date, the filter doesn't correctly display. I.E - if we have a batch that starts on 1/2/2018 and ends on 2/3/2018, trying to filter by the dates 1/2/2018 and 2/3/2018 for start and end respectively does not display the batch. Confirmed for admin user, not sure about the other users

**Comment by manus-andurkar** [comment]
I can give this a try.

**Comment by TaylorBrodowsky** [comment]
filter works now

**Comment by dvosecky** [comment]
Fixed by adding one to end date.
