### ISSUE TITLE
Update Trainer

### ISSUE THREAD

**Issue by Emaku** [revaturelabs/trackforce#742]
When updating trainer info through Trainer Homepage -> Home Tab, the information is not changed in the database. Missing proper HTTP Request and DB Communication.

**Comment by jckuhl** [comment]
Methods weren't implemented front end.  Fixed it on my end.  PR request inbound in a few minutes

**Comment by davidcheng1760** [comment]
trackforce/NGTrackForce/src/app/components/trainer-view/trainer-view.component.ts
The front end is not sending back the updated information! Moving the:
        this.trainer.firstName = this.newFirstName;
        this.trainer.lastName = this.newLastName;
Before you call the server to update to fix the issue.
