### ISSUE TITLE
Mapped vs Unmapped pie charts and Mapped do not respond to chart buttons

### ISSUE THREAD

**Issue by steveLoayza** [revaturelabs/trackforce#744]
### Description
The mapped vs unmapped pie charts (top right) do not respond to the different chart buttons

Steps to reproduce
1. Login as TestAdmin
2. Click mapped vs unmapped pie charts (top right chart)
3. Try clicking bar chart/ polar chart

**Comment by Vivi-Vo** [comment]
This feature works in production.

**Comment by erikmoore001** [comment]
Issue is NOT working in production. Only 'Unmapped' Graph functionality is working. The other 3 (Mapped, Mapped vs Unmapped [undeployed], Mapped vs Unmapped [deployed]) are disabled buttons.
