### ISSUE TITLE
Registering new Associate fails

### ISSUE THREAD

**Issue by panyardts1** [revaturelabs/trackforce#748]
Cannot register a new associate from the login page. Attempting to register an associate returns a response code of 500, and a NullPointerException on the server.

**Comment by Quinn-Donnelly** [comment]
Unable to reproduce your issue
![image](https://user-images.githubusercontent.com/8989563/44867908-2d7b7d00-ac57-11e8-9b9c-6b946321177a.png)

![image](https://user-images.githubusercontent.com/8989563/44867864-091fa080-ac57-11e8-882a-718a64ea1841.png)

**Comment by panyardts1** [comment]
Issue was only on my machine. Rebasing resolved the issue
