### ISSUE TITLE
Fix Eager Fetching with Database

### ISSUE THREAD

**Issue by jdpressley5** [revaturelabs/trackforce#756]
In src/main/entity classes

Some DAO entities fetch strategies are set to EAGER. This has the potential to cause performance issues, particularly 'one to many' fields. In particular: TfBatch.java - The associates and trainer fields are eager with the potential to cause a fetching loop

**Comment by jdpressley5** [comment]
Requires edits on front and backend to complete.
The frontend is expecting all data so lazy loading can't be assigned to more fields in the DaoImpl's
This needs to be a joint effort to resolve.

**Comment by mycluster** [comment]
Due to tightly coupled interactions between foreign keys, both tables are needed to be set to EAGER. 
We separately reset both the associate and batch IDs to LAZY, and they respectively cause the fetches to endlessly loop. No further changes are needed in the code-base for this issue.
