### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/trackforce#795]
## Description
The current application only has one module. Considering the size of the application and the multiple role system sending the client all of the JavaScript on first load is sub optimal. For security purposes the various roles should not receive the code that their role can't use. This will aid in performance as well as aid in some security risks that can occur due to bugs.

### Information
To begin to work on this I recommend checking out webpack-bundle-analyzer. This is an npm module that you can use to see what is in the bundles we are seeing sent to the client.

Currently this is the gzipped assets that are sent to the client on the login page.

![image](https://user-images.githubusercontent.com/8989563/45226566-2541c400-b28d-11e8-9561-96ef33037bb9.png)

#### Steps to Set Up
1. Get the cli `npm install -g webpack-bundle-analyzer`
2. Build the angular app with stats recording enabled `ng build --stats-json --build-optimizer=false --vendor-chunk=true`
3. Run the webpack-bundle-analyzer `webpack-bundle-analyzer dist/stats.json`
4. This will open a page that will show information about the bundle (See below)

![image](https://user-images.githubusercontent.com/8989563/45226394-b6fd0180-b28c-11e8-951d-d59a24a4bb78.png)

**Comment by JaxWLee** [comment]
Modularized the application
