### ISSUE TITLE
Adding new interview throws Hibernate error

### ISSUE THREAD

**Issue by jckuhl** [revaturelabs/trackforce#800]
## Description
Attempting to add a new interview as an associate throws a Hibernate exception.  Despite the exception, the POST returns a 201 and a `null` object to the client rather than an error.

    13:48:51 HibernateUtil.java:89 - ids for this class must be manually assigned before calling save(): com.revature.entity.TfInterview
    org.hibernate.id.IdentifierGenerationException: ids for this class must be manually assigned before calling save(): com.revature.entity.TfInterview

This part of the stack trace is our code:

	at com.revature.utils.HibernateUtil.lambda$1(HibernateUtil.java:26)
	at com.revature.utils.HibernateUtil.lambda$3(HibernateUtil.java:81)

## Steps to Reproduce

Log in as Cyril (or any associate)
Navigate to interview tab
Attempt to submit a new interview

**Comment by revcg** [comment]
Fixed by adding a call to the correct user in TFInterview resource.
