### ISSUE TITLE
Prediction List - Scrolling in Requirements generates too many rows in Resource Available Table

### ISSUE THREAD

**Issue by IMMcC4486** [revaturelabs/trackforce#871]
The Associates Needed column contains a numeric input field with the ability to scroll up and down. If you scroll too fast, the Resources Available table seemingly can't keep up and will generate extra rows.

**Comment by revcg** [comment]
Instead of making an HTTP request for every keystroke/click via change event, users make their changes then click check resources, which calls getAllPredictions.
