### ISSUE TITLE
Login Requires a Second Login Call

### ISSUE THREAD

**Issue by JaxWLee** [revaturelabs/trackforce#913]
In the login component, after fixing the local storage security issue we used a service to call the server and get the users role. Since that is asynchronous you originally had to hit the login button twice. We added a boolean if statement that called the login method again on your first login try. This works but is kind of hackey. Hopefully can be improved quite easily

**Comment by landonRmiller** [comment]
@dvosecky @PrososkiP @revcg Should this issue be closed? Thanks.

**Comment by revcg** [comment]
Resolved issue in login.component.ts by removing the call to login and set user role after a 10 millisecond delay.
