### ISSUE TITLE
Client Resource Security weakpoints

### ISSUE THREAD

**Issue by Bioshock667** [revaturelabs/trackforce#928]
Client Resource has failed the REST assured security tests.  Need to update token authentication and authorization for Client Resource so the endpoints verify tokens and check the role.

**Comment by BSlappey** [comment]
There is rewritten client resource class included in the 1809 documentation that passed the rest assured tests.  However we were unable to integrate it into our final version.  The new class will be included in the google drive

**Comment by lukasmckela** [comment]
This has already been completed
