### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by landonRmiller** [revaturelabs/trackforce#938]
TODO
1. Cleanup pom.xml: (SLF4j appears not to be used) (3 different SLF4j dependency)
2. Logging is missing from many classes.
3. Log in test utils used once, shouldn't be used because the class being logged will be of Log class, instead of class being logged.
4. LogUtil in main utils used, shouldn't be used because the class being logged will be of LogUtil class, instead of class being logged.
5. Troubleshoot general configuration problems.

Note that custom configuration is using target folder as location for writing log files.

**Comment by Szhao2** [comment]
pom.xml dependencies already fixed. Only 1 SLF4j used now
<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>2.11.1</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
these are the two log4j depdencies that currently exist

**Comment by Szhao2** [comment]
Loggers are now included in most Util Codes, All Resource End-Points, & DAO-Impl and related services that needed necessary loggers.
